### ISSUE TITLE
Config tags not being passed through

### ISSUE THREAD

**Issue by spamhandle** [bmhatfield/riemann-sumd#10]
Hiya,

It looks like there's maybe an issue with task tags not being unioned with config tags.
I'm not a python expert but this code snippet seems to not set the unioned result back into the t.tags variable.

loader.py (line 52)
                if additional_tags:
                    t.tags.union(set(additional_tags))

Am I correct or have I missed something?

**Comment by bmhatfield** [comment]
You are correct. It appears this should have been `.update()`.
